{
 "title": "Skills Extraction",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "run_id",
    "label": "run_id",
    "query": {
     "query": "label_values(ske_rows_total,run_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "N Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Worker Thread" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "1", "type": "math" }
   ]
  },
  {
   "title": "Total Rows",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ske_rows_total", "legendFormat": "{{keyword}}" }
   ]
  },
  {
   "title": "Change in Skills Extraction Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "changes(ske_time_sum[$__interval])"
    }
   ]
  },
  {
   "title": "Average Skills Extraction Time per Job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$sum / $count", "type": "math" }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "task.id: get_skills_from_jobs*",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "keyword", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }, "repeat": "keyword" },
  {
   "title": "Histogram of Skills extraction duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by(le) (ske_time_bucket)", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Progress : $keyword",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ske_rows_total" },
    { "expr": "ske_rows_processed_total" }
   ]
  }
 ]
}