{
 "title": "TalendJobsETL",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "run_id",
    "label": "Airflow Run Identifier",
    "query": {
     "query": "label_values(work_time_total,run_id)"
    }
   },
   {
    "name": "job_instance",
    "label": "job_instance",
    "query": {
     "query": "label_values(work_time_total{run_id=\"$run_id\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "job.talend_job : *",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "$job_instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "job_instance" },
  {
   "title": "Status : $job_instance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "work_time_total{instance=~\"$job_instance\", component!~\"t.*\", run_id=\"$run_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rows Stats",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(label) (rows_total{job=\"some_talend_job\", instance=~\"$job_instance\", run_id=\"$run_id\", label!=\"source\"})"
    },
    {
     "expr": "max by(label) (rows_total{job=\"some_talend_job\", instance=~\"$job_instance\", run_id=\"$run_id\", label=\"source\"})",
     "legendFormat": "source"
    }
   ]
  },
  {
   "title": "Status Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "work_time_total{instance=\"$job_instance\", component!~\"t.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Historical Data",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "work_time_total{instance=\"$job_instance\", component!~\"t.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Duration : $job_instance",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "work_time_total{job=\"some_talend_job\", instance=~\"$job_instance\", run_id=\"$run_id\"}",
     "legendFormat": "{{component}} Total"
    }
   ]
  },
  {
   "title": "Total Duration : $job_instance",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "work_time_total{job=\"some_talend_job\", instance=~\"$job_instance\", run_id=\"$run_id\"}",
     "legendFormat": "{{component}} Total"
    }
   ]
  }
 ]
}