{
 "title": "Web Scrapping",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "keyword",
    "label": "Keyword",
    "query": {
     "query": "label_values(scrap_pages_total,keyword)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "N Threads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Worker Thread" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scrap_worker_num_total" }
   ]
  },
  {
   "title": "Total Pages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scrap_pages_total", "legendFormat": "{{keyword}}" }
   ]
  },
  {
   "title": "Local",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Local" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scrap_local_total" }
   ]
  },
  {
   "title": "Total Keywords",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Keyword" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scrap_keywords_total" }
   ]
  },
  {
   "title": "Average scrap job duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$sum / $count", "type": "math" }
   ]
  },
  {
   "title": "Change in job scrap duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "changes(scrap_jobs_duration_sum[$__interval])"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "task.id: hello_work_scrap_data*",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "$keyword", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }, "repeat": "keyword" },
  {
   "title": "Histogram of scrapping job duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (scrap_jobs_duration_bucket{keyword=\"$keyword\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Progress : $keyword",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scrap_pages_total{keyword=~\"$keyword\"}"
    },
    {
     "expr": "scrap_pages_current_total{keyword=~\"$keyword\"}"
    }
   ]
  }
 ]
}