{
 "title": "Company scrap",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "keyword",
    "label": "Keyword",
    "query": {
     "query": "label_values(scrap_pages_total,keyword)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "N Threads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Worker Thread" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "company_worker_num_total" }
   ]
  },
  {
   "title": "Total Companies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "company_count_total", "legendFormat": "{{keyword}}" }
   ]
  },
  {
   "title": "Change in copany scrapping duration",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "changes(company_scrap_duration_sum[$__interval])"
    }
   ]
  },
  {
   "title": "Average company scrapping duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$sum / $count", "type": "math" }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "task.id: company_details_scrap*",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "$keyword", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }, "repeat": "keyword" },
  {
   "title": "Histogram of scrapping company duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (company_scrap_duration_bucket)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Progress ",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "company_count_total" },
    { "expr": "company_details_scrapped_total" }
   ]
  },
  {
   "title": "Progress ",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "company_count_total" },
    {
     "expr": "company_financial_scrapped_total"
    }
   ]
  }
 ]
}